Map<String, String> enUS = {
  'app_title': 'Gutendex Books App',
  'gutenberg_project_title': 'Gutenberg Project',
  'gutenberg_project_subtitle': 'A social cataloging website that allows you to freely search its database of books, annotations, and reviews.',
  'explore_books_by_genre': 'Explore Books by Genre',
  'select_category_to_read': 'Select a category to find your next read.',
  'all_books_title': 'All Books',
  'search_hint': 'Search',
  'search_by_title_or_author': 'Search by title or author...',
  'no_books_found': 'No books found.',
  'error': 'Error',
  'failed_to_load_books': 'Failed to load books: ',
  'could_not_launch_url': 'Could not launch ',
  'no_viewable_version_available': 'No viewable version available',
  'category_fiction': 'Fiction',
  'category_drama': 'Drama',
  'category_humour': 'Humour',
  'category_politics': 'Politics',
  'category_philosophy': 'Philosophy',
  'category_history': 'History',
  'category_adventure': 'Adventure',
  'category_romance': 'Romance',
  'category_science': 'Science',
  'category_fantasy': 'Fantasy',
  'category_mystery': 'Mystery',
  'category_thriller': 'Thriller',
  'category_horror': 'Horror',
  'category_biography': 'Biography',
  'category_religion': 'Religion',
  'category_children': 'Children',
};